import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { i18n, type Locale } from "../../i18n-config";

import theme from "../utils/theme";
import { getDictionary } from "@/get-dictionary";
import { I18nContextProvider } from "@/contexts/I18nContext";
import { DrawerContextProvider } from "@/contexts/DrawerContext";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function Root({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang} className="dark">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <I18nContextProvider dictionary={dictionary}>
              <DrawerContextProvider>{children}</DrawerContextProvider>
            </I18nContextProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Pokemon Go Pokedex",
  description: "Generated by create next app",
};
